#!/usr/bin/python
port boto3
import base64
import pprint

ec2 = boto3.resource('ec2')
client = boto3.client('ec2')

amazon_image = 'ami-2051294a'                                       # This will launch a red hat instance
amazon_instance = 't2.micro'                                        # we've been working with micro's, if you use Amizon Linux, you could launch a nono
amazon_pem_key = 'Simba'                    # the name of the key/pem file you would like to use to access this machine
firewall_profiles = ['launch-wizard-3']                             # the security group name(s) you would like to use, remember, this is your firewall, make sure the ports you want open are open

print(amazon_image)
print(amazon_instance)
print(amazon_pem_key)

def launch_test_instance():

   instances = ec2.create_instances(
      ImageId = amazon_image,
      InstanceType = amazon_instance,
      MinCount=1,
      MaxCount=1,
      KeyName = amazon_pem_key,
      SecurityGroupIds = firewall_profiles,
      
      UserData="""#!/usr/bin/python
import sys, os
# your script here
def install_django():
   print('installing django')
install_django()
def install_pip():
        os.system('yum -y install python-pip')
        print('installing python-pip')
install_pip()
def install_virtualenv():
        os.system('cd /opt')
        os.system('pip install virtualenv')
        os.system('virtualenv django-env')
        print('installing virtual-env')
install_virtualenv()
# This is activating the django
def activate_virtualenv():

        os.system('which python')
        os.system('pip install django')
        os.system('django-admin --version')
        os.system('django-admin startproject project1; exists_ok=true')
        os.system('tree project1')
        print('installing tree')
        print('installing django')
        os.system('source /opt/django/django-env/bin/activate && python /opt/django/project1/ manage.py runserver 0.0.0.0:8000&')
        print('done')


activate_virtualenv()
"""
       )
   pprint.pprint(instances)

launch_test_instance()
 
      

